In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from dotenv import load_dotenv
import os
load_dotenv()

True

In [4]:
df =pd.read_csv("data/patient_data.csv")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head(5)

Rows: 100
Columns: 18

,patient_id,patient_name,age,gender,diagnosis,current_medication,lab_test,lab_value,lab_unit,last_visit_date,next_scheduled_visit,days_since_last_visit,missed_last_appointment,vitals_bp_systolic,vitals_bp_diastolic,vitals_heart_rate,vitals_spo2,notes
0,P0001,Aarav Sharma,68,Male,Type 2 Diabetes,Metformin 500mg,HbA1c,9.9,%,2024-04-24,2024-06-08,251,No,174,70,95,96,Patient reports good medication adherence.
1,P0002,Priya Patel,29,Male,Heart Failure,Furosemide 40mg,BNP,317.6,pg/mL,2024-01-14,2024-02-28,352,No,174,91,72,97,Patient reports no new symptoms.
2,P0003,Rohan Mehta,45,Male,"Type 2 Diabetes, CKD","Insulin Glargine 10U, Losartan 50mg",HbA1c,11.4,%,2024-08-04,2024-10-03,149,No,132,86,64,91,Medication dose adjusted this visit.
3,P0004,Anjali Singh,34,Female,"COPD, Heart Failure","Tiotropium 18mcg, Furosemide 40mg",FEV1%,33.8,%,2024-01-23,2024-04-22,343,No,153,70,93,94,Patient reports no new symptoms.
4,P0005,Vikram Nair,51,Male,"Hypertension, Heart Failure","Amlodipine 5mg, Furosemide 40mg",BP Systolic,124.9,mmHg,2024-04-26,2024-06-25,249,No,134,71,82,94,Patient education provided on diet and lifestyle.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   patient_id               100 non-null    str
 1   patient_name             100 non-null    str
 2   age                      100 non-null    int64
 3   gender                   100 non-null    str
 4   diagnosis                100 non-null    str
 5   current_medication       100 non-null    str
 6   lab_test                 100 non-null    str
 7   lab_value                100 non-null    float64
 8   lab_unit                 100 non-null    str
 9   last_visit_date          100 non-null    str
 10  next_scheduled_visit     100 non-null    str
 11  days_since_last_visit    100 non-null    int64
 12  missed_last_appointment  100 non-null    str
 13  vitals_bp_systolic       100 non-null    int64
 14  vitals_bp_diastolic      100 non-null    int64
 15  vitals_heart_rate        100 non-null    int64
 16  vitals_spo2              100 non-null    int64
 17  notes                    100 non-null    str
dtypes: float64(1), int64(6), str(11)
memory usage: 14.2 KB

In [6]:
df.isnull().sum()

patient_id                 0
patient_name               0
age                        0
gender                     0
diagnosis                  0
current_medication         0
lab_test                   0
lab_value                  0
lab_unit                   0
last_visit_date            0
next_scheduled_visit       0
days_since_last_visit      0
missed_last_appointment    0
vitals_bp_systolic         0
vitals_bp_diastolic        0
vitals_heart_rate          0
vitals_spo2                0
notes                      0
dtype: int64

In [7]:
df.describe()

,age,lab_value,days_since_last_visit,vitals_bp_systolic,vitals_bp_diastolic,vitals_heart_rate,vitals_spo2
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,55.360000,150.810000,211.390000,145.570000,87.680000,82.420000,94.500000
std,15.251773,279.918492,87.498675,20.375889,13.625496,14.460102,2.794294
min,28.000000,1.700000,65.000000,105.000000,65.000000,58.000000,90.000000
25%,44.000000,9.675000,132.500000,130.000000,75.750000,72.000000,92.000000
50%,55.000000,34.950000,219.000000,145.500000,87.500000,83.000000,95.000000
75%,68.000000,144.600000,287.750000,161.250000,99.250000,95.000000,97.000000
max,82.000000,1164.000000,360.000000,181.000000,110.000000,108.000000,99.000000